---
prompt_file: data/qasa_prompt.json
eval_file: data/qasa_eval.json
shot: 2
ndoc: 3
dataset_name: qasa
tag: openrouter
model: meta-llama/llama-3.3-70b-instruct:free
openai_api: false
openrouter_api: true
openrouter_reasoning: false