---
prompt_file: data/qasa_prompt.json
eval_file: data/qasa_eval.json
shot: 2
ndoc: 5
dataset_name: qasa
tag: openrouter
model: google/gemma-4-31b-it:free
openai_api: false
openrouter_api: true
openrouter_reasoning: false